"""Anonymity: sever identity from sessions, add report retrieval tables

Drops respondent_sessions.user_id so responses can never be joined to a named
member, and adds the capability-token retrieval tables (report_deliveries,
user_report_tokens). See docs/anonymity-design.md.

Revision ID: 0002_anonymity
Revises: 0001_initial
Create Date: 2026-06-18 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "0002_anonymity"
down_revision: Union[str, None] = "0001_initial"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ── Sever identity from survey sessions ───────────────────────────────────
    # The FK constraint name is autogenerated by the 0001 create_table; drop by
    # column with the standard naming, tolerating absence on fresh DBs.
    with op.batch_alter_table("respondent_sessions") as batch:
        batch.drop_constraint("respondent_sessions_user_id_fkey", type_="foreignkey")
        batch.drop_column("user_id")

    # anonymous_token is now the sole, required identifier for a session.
    op.alter_column(
        "respondent_sessions", "anonymous_token",
        existing_type=sa.String(255), nullable=False,
    )
    op.create_unique_constraint(
        "uq_respondent_sessions_anonymous_token", "respondent_sessions", ["anonymous_token"]
    )
    op.create_index(
        "ix_respondent_sessions_anonymous_token", "respondent_sessions", ["anonymous_token"]
    )

    # ── Report delivery (email) — severed from church_id AND user_id ──────────
    op.create_table(
        "report_deliveries",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("session_token", sa.String(255), nullable=False),
        sa.Column("email", sa.String(255), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()")),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_report_deliveries_session_token", "report_deliveries", ["session_token"])

    # ── Optional account keyring — opaque tokens, keyed from the user side ─────
    op.create_table(
        "user_report_tokens",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("session_token", sa.String(255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()")),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_user_report_tokens_user_id", "user_report_tokens", ["user_id"])


def downgrade() -> None:
    op.drop_index("ix_user_report_tokens_user_id", table_name="user_report_tokens")
    op.drop_table("user_report_tokens")

    op.drop_index("ix_report_deliveries_session_token", table_name="report_deliveries")
    op.drop_table("report_deliveries")

    op.drop_index("ix_respondent_sessions_anonymous_token", table_name="respondent_sessions")
    op.drop_constraint(
        "uq_respondent_sessions_anonymous_token", "respondent_sessions", type_="unique"
    )
    op.alter_column(
        "respondent_sessions", "anonymous_token",
        existing_type=sa.String(255), nullable=True,
    )
    op.add_column(
        "respondent_sessions",
        sa.Column("user_id", sa.String(), nullable=True),
    )
    op.create_foreign_key(
        "respondent_sessions_user_id_fkey", "respondent_sessions", "users", ["user_id"], ["id"]
    )
